#!/usr/bin/env php 
<?php

include "src/CssMin.php";
if (!isset($argv[1])) {
    die(
        'Usage: cssmin file' . PHP_EOL
    );
}

if (!file_exists($argv[1])) {
    die(
        'cssmin: cannot minify ' . $argv[1] . ': No such file or directory' . PHP_EOL
    );
}

print cssmin::minify(file_get_contents($argv[1]));
